name: Fuel Forecast Bot

on:
  schedule:
    - cron: '* * * * *'   # every minute - testing
  workflow_dispatch:  

jobs:
  send-forecast:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Fuel Forecast Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        shell: pwsh
        run: ./Send-FuelForecastTelegram.ps1
